# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  paymentsystem:
    image: paymentsystem
    build:
      context: .
      dockerfile: PaymentSystem/Dockerfile
    ports:
      - 5000